# backend/models/programacao.py
"""
Operational programacao models.

The column names mirror the desktop SQLite schema so the browser flow can share
the same operational vocabulary used by ProgramacaoPage in main.py.
"""
from sqlalchemy import Column, Float, Integer, String

from backend.config.database import Base


class ProgramacaoDB(Base):
    __tablename__ = "programacoes"

    id = Column(Integer, primary_key=True, index=True)
    codigo_programacao = Column(String, unique=True, index=True, nullable=False)
    codigo = Column(String, index=True)
    data = Column(String)
    data_criacao = Column(String)
    motorista = Column(String, nullable=False)
    motorista_id = Column(Integer)
    motorista_codigo = Column(String, index=True)
    codigo_motorista = Column(String)
    veiculo = Column(String, nullable=False)
    equipe = Column(String)
    kg_estimado = Column(Float, default=0)
    tipo_estimativa = Column(String, default="KG")
    caixas_estimado = Column(Integer, default=0)
    operacao_tipo = Column(String, default="VENDA")
    transbordo_modalidade = Column(String)
    transbordo_observacao = Column(String)
    transbordo_grupo = Column(String)
    status = Column(String, default="ATIVA", index=True)
    status_operacional = Column(String)
    status_operacional_obs = Column(String)
    status_operacional_em = Column(String)
    status_operacional_por = Column(String)
    finalizada_no_app = Column(Integer, default=0)
    prestacao_status = Column(String, default="PENDENTE")
    local_rota = Column(String)
    tipo_rota = Column(String)
    local_carregamento = Column(String)
    granja_carregada = Column(String)
    local_carregado = Column(String)
    local_carreg = Column(String)
    num_nf = Column(String)
    nf_numero = Column(String)
    saida_data = Column(String)
    saida_hora = Column(String)
    data_saida = Column(String)
    hora_saida = Column(String)
    saida_dt = Column(String)
    inicio_carregamento = Column(String)
    fim_carregamento = Column(String)
    carregamento_fechado = Column(Integer, default=0)
    carregamento_salvo_em = Column(String)
    data_chegada = Column(String)
    hora_chegada = Column(String)
    chegada_dt = Column(String)
    diaria_motorista_valor = Column(Float, default=0)
    adiantamento = Column(Float, default=0)
    adiantamento_rota = Column(Float, default=0)
    adiantamento_origem = Column(String)
    kg_carregado = Column(Float, default=0)
    caixas_carregadas = Column(Integer, default=0)
    qnt_cx_carregada = Column(Integer, default=0)
    media = Column(Float, default=0)
    qnt_aves_por_cx = Column(Integer, default=0)
    qnt_aves_caixa_final = Column(Integer, default=0)
    aves_caixa_final = Column(Integer, default=0)
    media_1 = Column(Float)
    media_2 = Column(Float)
    media_3 = Column(Float)
    km_inicial = Column(Float, default=0)
    km_final = Column(Float, default=0)
    km_rodado = Column(Float, default=0)
    litros = Column(Float, default=0)
    media_km_l = Column(Float, default=0)
    custo_km = Column(Float, default=0)
    mortalidade_transbordo_aves = Column(Integer, default=0)
    mortalidade_transbordo_kg = Column(Float, default=0)
    obs_transbordo = Column(String)
    foto_doa_path = Column(String)
    doa_foto_path = Column(String)
    mortalidade_transbordo_foto_path = Column(String)
    foto_doa_ref_json = Column(String)
    ajudantes_alteracao_motivo = Column(String)
    ajudantes_alterado_em = Column(String)
    historico_ajudantes = Column(String)
    rota_observacao = Column(String)
    ced_200_qtd = Column(Integer, default=0)
    ced_100_qtd = Column(Integer, default=0)
    ced_50_qtd = Column(Integer, default=0)
    ced_20_qtd = Column(Integer, default=0)
    ced_10_qtd = Column(Integer, default=0)
    ced_5_qtd = Column(Integer, default=0)
    ced_2_qtd = Column(Integer, default=0)
    valor_dinheiro = Column(Float, default=0)
    pix_motorista = Column(Float, default=0)
    usuario_criacao = Column(String)
    usuario_ultima_edicao = Column(String)
    total_caixas = Column(Integer, default=0)
    quilos = Column(Float, default=0)
    nf_kg = Column(Float, default=0)
    kg_nf = Column(Float, default=0)
    nf_preco = Column(Float, default=0)
    preco_nf = Column(Float, default=0)
    nf_caixas = Column(Integer, default=0)
    nf_kg_carregado = Column(Float, default=0)
    nf_kg_vendido = Column(Float, default=0)
    nf_saldo = Column(Float, default=0)
    company_id = Column(Integer)


class ProgramacaoItemDB(Base):
    __tablename__ = "programacao_itens"

    id = Column(Integer, primary_key=True, index=True)
    codigo_programacao = Column(String, index=True, nullable=False)
    cod_cliente = Column(String, index=True, nullable=False)
    nome_cliente = Column(String, nullable=False)
    qnt_caixas = Column(Integer, default=0)
    kg = Column(Float, default=0)
    preco = Column(Float, default=0)
    endereco = Column(String)
    vendedor = Column(String)
    pedido = Column(String)
    produto_id = Column(Integer, index=True)
    produto = Column(String)
    observacao = Column(String)
    status_pedido = Column(String)
    caixas_atual = Column(Integer)
    preco_atual = Column(Float)
    alterado_em = Column(String)
    alterado_por = Column(String)
    ordem_sugerida = Column(Integer)
    eta = Column(String)
    distancia = Column(Float)
    confianca_localizacao = Column(Float)
    carga_raiz_programacao = Column(String)
    carga_origem_imediata = Column(String)
    transferencia_origem_id = Column(String)
    company_id = Column(Integer)


class ProgramacaoItemControleDB(Base):
    __tablename__ = "programacao_itens_controle"

    id = Column(Integer, primary_key=True, index=True)
    codigo_programacao = Column(String, index=True)
    cod_cliente = Column(String, index=True)
    pedido = Column(String)
    status_pedido = Column(String)
    alteracao_tipo = Column(String)
    alteracao_detalhe = Column(String)
    caixas_atual = Column(Integer)
    preco_atual = Column(Float)
    alterado_em = Column(String)
    alterado_por = Column(String)
    mortalidade_aves = Column(Integer, default=0)
    media_aplicada = Column(Float)
    peso_previsto = Column(Float, default=0)
    valor_recebido = Column(Float, default=0)
    forma_recebimento = Column(String)
    obs_recebimento = Column(String)
    lat_evento = Column(Float)
    lon_evento = Column(Float)
    lat_entrega = Column(Float)
    lon_entrega = Column(Float)
    accuracy_entrega = Column(Float)
    timestamp_entrega = Column(String)
    endereco_evento = Column(String)
    cidade_evento = Column(String)
    bairro_evento = Column(String)
    foto_mortalidade_path = Column(String)
    mortalidade_foto_path = Column(String)
    foto_mortalidade_ref_json = Column(String)
    ordem_sugerida = Column(Integer)
    eta = Column(String)
    distancia = Column(Float)
    confianca_localizacao = Column(Float)
    updated_at = Column(String)
    company_id = Column(Integer)


class ProgramacaoItemLogDB(Base):
    __tablename__ = "programacao_itens_log"

    id = Column(Integer, primary_key=True, index=True)
    codigo_programacao = Column(String, index=True, nullable=False)
    cod_cliente = Column(String, index=True, nullable=False)
    pedido = Column(String)
    evento = Column(String, default="cliente_controle")
    payload_json = Column(String, nullable=False)
    registrado_em = Column(String)
    created_at = Column(String)
    company_id = Column(Integer)
